version: "3.9"

services:
  postgres-tests:
    image: postgres:16-alpine
    container_name: sonirama-postgres-tests
    restart: unless-stopped
    environment:
      POSTGRES_DB: sonirama_tests
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: change_me
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "55432:5432"
    volumes:
      - postgres_data_tests:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  postgres_data_tests:
    driver: local
